@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "EmbaralharPalavras.FabricaDeEmbaralhadores",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1067759703 { 
   	label=EmbaralharPalavras
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   EmbaralharAleatório1067759703[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EmbaralharAleatório</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ embaralhar(palavra: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EmbaralharInverso1067759703[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EmbaralharInverso</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ embaralhar(palavra: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EmbaralharPrimeiroParDepoisImpar1067759703[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EmbaralharPrimeiroParDepoisImpar</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ embaralhar(palavra: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FabricaDeEmbaralhadores1067759703[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FabricaDeEmbaralhadores</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   random: Random [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ embaralhador(palavra: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ embaralhar(palavra: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1527553641 { 
   	label=EmaralharPalavras
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   TesteEmbaralharPalavras1927468837[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TesteEmbaralharPalavras</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   embaralharAleatório: EmbaralharAleatório [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   embaralharInverso: EmbaralharInverso [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   embaralharParesDepoisImpares: EmbaralharPrimeiroParDepoisImpar [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fabricaDeEmbaralhadores: FabricaDeEmbaralhadores [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   palavra: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   random: Random [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ testeEmbaralhador()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testeEmbaralhadorInverso()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testeEmbaralhar()</TD></TR>
<TR><TD ALIGN="LEFT" >+ testeEmbaralharParesDepoisImpares()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
EmbaralharAleatório1067759703 -> EmbaralharInverso1067759703[arrowhead=none];
EmbaralharAleatório1067759703 -> EmbaralharPrimeiroParDepoisImpar1067759703[arrowhead=none];
EmbaralharAleatório1067759703 -> FabricaDeEmbaralhadores1067759703[arrowhead=none];
FabricaDeEmbaralhadores1067759703 -> EmbaralharAleatório1067759703[arrowhead=none];
FabricaDeEmbaralhadores1067759703 -> EmbaralharAleatório1067759703[label="embaralhador() -> embaralhar()"];
FabricaDeEmbaralhadores1067759703 -> EmbaralharInverso1067759703[arrowhead=none];
FabricaDeEmbaralhadores1067759703 -> EmbaralharInverso1067759703[label="embaralhador() -> embaralhar()"];
FabricaDeEmbaralhadores1067759703 -> EmbaralharPrimeiroParDepoisImpar1067759703[arrowhead=none];
FabricaDeEmbaralhadores1067759703 -> EmbaralharPrimeiroParDepoisImpar1067759703[label="embaralhador() -> embaralhar()"];
TesteEmbaralharPalavras1927468837 -> EmbaralharAleatório1067759703[label="embaralharAleatório
[0..1]"];
TesteEmbaralharPalavras1927468837 -> EmbaralharInverso1067759703[label="embaralharInverso
[0..1]"];
TesteEmbaralharPalavras1927468837 -> EmbaralharPrimeiroParDepoisImpar1067759703[label="embaralharParesDepoisImpares
[0..1]"];
TesteEmbaralharPalavras1927468837 -> FabricaDeEmbaralhadores1067759703[label="fabricaDeEmbaralhadores
[0..1]"];
    
}
@enduml