@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Jogo.DeDezAcaba",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_136677366 { 
   	label=FontePalavras
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   BancoDePalavras136677366[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BancoDePalavras</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   arquivo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   palavras: List&lt;String&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- lerArquivo(arquivo: String): List&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2314509 { 
   	label=Jogo
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CincoChances2314509[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CincoChances</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   arquivo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   banco: BancoDePalavras [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gameover: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   passouDeFase: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pontos: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   resultadoRespostaDavez: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tentativas: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acabouJogo(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ acertouResposta(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ instrucoes(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ modoDeJogo(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ palavraDaVez(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ passouDeFase(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ respostaDaVez(palavra: String, resposta: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ resultadoFinal(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DeDezAcaba2314509[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DeDezAcaba</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   arquivo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   banco: BancoDePalavras [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   passouDeFase: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pontos: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tentativas: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   terminou: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acabouJogo(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ acertouResposta(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ instrucoes(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ modoDeJogo(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ palavraDaVez(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ passouDeFase(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ respostaDaVez(palavra: String, resposta: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ resultadoFinal(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ErrouAcabou2314509[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ErrouAcabou</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   arquivo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   banco: BancoDePalavras [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   errou: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pontos: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   resultadoRespostaDavez: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tentativas: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acabouJogo(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ acertouResposta(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ instrucoes(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ modoDeJogo(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ palavraDaVez(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ passouDeFase(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ respostaDaVez(palavra: String, resposta: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ resultadoFinal(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
CincoChances2314509 -> BancoDePalavras136677366[label="banco
[0..1]"];
DeDezAcaba2314509 -> BancoDePalavras136677366[label="banco
[0..1]"];
DeDezAcaba2314509 -> CincoChances2314509[arrowhead=none];
DeDezAcaba2314509 -> ErrouAcabou2314509[arrowhead=none];
ErrouAcabou2314509 -> BancoDePalavras136677366[label="banco
[0..1]"];
    
}
@enduml